server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql:///mybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  application:
    name: service-provider #微服务名称
mybatis:
  type-aliases-package: cn.itcast.service.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka  #连接eureka注册中心